sudo: false
env:
  - CXX=g++-4.8
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
language: node_js
node_js:
 - 4
 - 5
 - 6
script:
 - npm install
 - gulp build
 - npm run lint
 - cd packages/mjml-parser-xml
 - npm link
 - npm install
 - npm test
